MLIR: lib/Dialect/Linalg/Transforms/ComprehensiveBufferize.cpp File Reference
ComprehensiveBufferize.cpp File Reference
#include "PassDetail.h"
#include "mlir/Analysis/SliceAnalysis.h"
#include "mlir/Dialect/Linalg/IR/LinalgOps.h"
#include "mlir/Dialect/Linalg/Passes.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/Dialect/Vector/VectorOps.h"
#include "mlir/IR/Operation.h"
#include "mlir/Pass/Pass.h"
#include "mlir/Transforms/BufferUtils.h"
#include "llvm/ADT/ScopeExit.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/ADT/TypeSwitch.h"
Macros
#define DEBUG_TYPE "comprehensive-func-bufferize"
#define DBGS() (llvm::dbgs() << '[' << DEBUG_TYPE << "] ")
Enumerations
enum InPlaceSpec { InPlaceSpec::False, InPlaceSpec::True, InPlaceSpec::None }
Functions
OpResult getMatchingOpResult (LinalgOp linalgOp, OpOperand &opOperand)
Return the OpResult that matches an operand.
OpResult getMatchingOpResult (VectorTransferOpInterface op, OpOperand &opOperand)
Return the OpResult that matches an operand.
OpResult getMatchingOpResult (SubTensorInsertOp op, OpOperand &opOperand)
Return the OpResult that matches an operand.
OpResult getMatchingOpResult (OpOperand &opOperand)
Determine which results may be reused inplace by the bufferization patterns of bufferizeFuncOpInternals.
static StringRef stringify (InPlaceSpec val)
static Optional< InPlaceSpec > symbolize (StringRef str)
static void setInPlaceOpResult (OpResult opResult, InPlaceSpec inPlace=InPlaceSpec::True)
Mark whether OpResult can actually be bufferized inplace.
static InPlaceSpec getInPlace (OpResult opResult)
Get the InPlaceSpec attribute entry kInPlaceResultsAttrName for opResult.
static InPlaceSpec getInPlace (BlockArgument bbArg)
Get inPlace information for bbArg.
static void map (BlockAndValueMapping &bvm, ValueRange keys, ValueRange values)
Wrapper for better debugging.
static void map (BlockAndValueMapping &bvm, Value key, Value value)
Wrapper for better debugging.
static Value lookup (BlockAndValueMapping &bvm, Value key)
Wrapper for better debugging.
static MemRefType getContiguousMemRefType (ShapedType shapedType, ArrayRef< AffineMap > layout={}, unsigned addressSpace=0)
Return a contiguous MemRefType (i.e.
static Type getContiguousOrUnrankedMemRefType (Type type, ArrayRef< AffineMap > layout={}, unsigned addressSpace=0)
Return a contiguous MemRefType (i.e.
static MemRefType getDynamicMemRefType (RankedTensorType tensorType, unsigned addressSpace=0)
Return a MemRefType to which the tensorType can be bufferized in a composable fashion.
static Value createNewAllocDeallocPairForShapedValue (OpBuilder &b, Location loc, Value shapedValue, SmallVector< Value, 4 > dynOperands={})
Create an Allocop/DeAllocOp pair, where the AllocOp is after shapedValue.getDefiningOp (or at the top of the block in case of a bbArg) and the DeallocOp is at the end of the block.
static LogicalResult allocateBuffersForResults (OpBuilder &b, Location loc, LinalgOp op, SmallVectorImpl< Value > &resultBuffers, BlockAndValueMapping &bvm)
Helper function for LinalgOp bufferization.
static void finalizeBufferAllocation (OpBuilder &b, LinalgOp op, ValueRange inputs, ValueRange outputs, BlockAndValueMapping &bvm)
static LogicalResult bufferize (OpBuilder &b, LinalgOp op, BlockAndValueMapping &bvm)
Generic conversion for any LinalgOp.
static LogicalResult bufferize (OpBuilder &b, memref::DimOp dimOp, BlockAndValueMapping &bvm)
DimOp tensor operand is modified inplace.
static LogicalResult bufferize (OpBuilder &b, FuncOp funcOp, BlockAndValueMapping &bvm)
FuncOp always creates TensorToMemRef ops.
static LogicalResult bufferize (OpBuilder &b, ReturnOp returnOp, BlockAndValueMapping &bvm)
ReturnOp always creates memref::TensorLoadOp.
static LogicalResult bufferize (OpBuilder &b, SubTensorOp subTensorOp, BlockAndValueMapping &bvm)
Bufferize SubTensorOp to subview with optional alloc + copy depending on whether or not it is marked inplaceable.
static LogicalResult bufferize (OpBuilder &b, SubTensorInsertOp subTensorInsertOp, BlockAndValueMapping &bvm)
static LogicalResult bufferize (OpBuilder &b, VectorTransferOpInterface op, BlockAndValueMapping &bvm)
bool hasInterferingTensorRead (OpOperand &opOperand, const DominanceInfo &domInfo)
Determine whether any subsequent read of the tensor opOperand may occur.
static bool bufferizeToWriteable (OpOperand &opOperand)
Return false if either:
static bool isBufferizableInPlace (OpOperand &opOperand, const DominanceInfo &domInfo)
Return false if either:
static bool bufferizeToReadOnly (OpOperand &operand)
Return true if operand bufferizes to a buffer that is known to never be written.
static bool subTensorUseBufferizesToReadOnly (OpOperand &operand)
Assume operand is a use of a subTensorOp.
static bool dominatesAllOtherUses (OpOperand &dominator, const DominanceInfo &domInfo)
Return true if dominator.getOwner() dominates all other uses of dominator.get().
static void analyzeInPlaceSubTensor (SubTensorOp subTensorOp, const DominanceInfo &domInfo)
SubTensorOp introduces potential aliasing and a combination of things need to occur to determine whether it is inplaceable.
static void inPlaceAnalysisFuncOpInternals (FuncOp funcOp, const DominanceInfo &domInfo)
Analyze the internals of a FuncOp to determine inplaceable ops.
static LogicalResult bufferizeFuncOpInternals (FuncOp funcOp, BlockAndValueMapping &bvm, const DenseMap< FuncOp, SmallVector< int64_t >> &tiedResultsMap)
Variables
constexpr StringLiteral kInPlaceResultsAttrName = "__inplace_results_attr__"
Attribute marker to specify op results that can be bufferized inPlace.
Macro Definition Documentation
DBGS
#define DBGS () (llvm::dbgs() << '[' << DEBUG_TYPE << "] ")
Definition at line 100 of file ComprehensiveBufferize.cpp.
Referenced by bufferize(), bufferizeFuncOpInternals(), hasInterferingTensorRead(), inPlaceAnalysisFuncOpInternals(), map(), and setInPlaceOpResult().
DEBUG_TYPE
#define DEBUG_TYPE "comprehensive-func-bufferize"
Definition at line 94 of file ComprehensiveBufferize.cpp.
Enumeration Type Documentation
InPlaceSpec
enum InPlaceSpec strong
Enumerator
False
True
None
Definition at line 178 of file ComprehensiveBufferize.cpp.
Function Documentation
allocateBuffersForResults()
static LogicalResult allocateBuffersForResults (OpBuilder & b, Location loc, LinalgOp op, SmallVectorImpl< Value > & resultBuffers, BlockAndValueMapping & bvm) static
Helper function for LinalgOp bufferization.
Operate on mixed tensor + buffer Linalg ops for progressive bufferization. Allocate the output buffers for the remaining tensor output operands of the Linalg op. If the tensor is an "init" tensor (i.e. its value is actually used in the payload region), we additionally copy the original value into the newly allocated buffer.
Definition at line 407 of file ComprehensiveBufferize.cpp.
References mlir::OpBuilder::create(), createNewAllocDeallocPairForShapedValue(), mlir::failure(), mlir::Value::getDefiningOp(), getInPlace(), getMatchingOpResult(), mlir::Value::getType(), mlir::Type::isa(), lookup(), mlir::BlockAndValueMapping::lookupOrDefault(), map(), mlir::OpBuilder::setInsertionPointAfter(), mlir::success(), and True.
Referenced by bufferize().
analyzeInPlaceSubTensor()
static void analyzeInPlaceSubTensor (SubTensorOp subTensorOp, const DominanceInfo & domInfo) static
SubTensorOp introduces potential aliasing and a combination of things need to occur to determine whether it is inplaceable.
Definition at line 848 of file ComprehensiveBufferize.cpp.
References dominatesAllOtherUses(), setInPlaceOpResult(), subTensorUseBufferizesToReadOnly(), and True.
Referenced by inPlaceAnalysisFuncOpInternals().
bufferize() [1/7]
static LogicalResult bufferize (OpBuilder & b, LinalgOp op, BlockAndValueMapping & bvm) static
Generic conversion for any LinalgOp.
Operate on mixed tensor + buffer Linalg ops for progressive bufferization.
Definition at line 475 of file ComprehensiveBufferize.cpp.
References allocateBuffersForResults(), DBGS, mlir::failed(), mlir::failure(), finalizeBufferAllocation(), lookup(), mlir::OpBuilder::setInsertionPoint(), and mlir::success().
Referenced by bufferizeFuncOpInternals().
bufferize() [2/7]
static LogicalResult bufferize (OpBuilder & b, memref::DimOp dimOp, BlockAndValueMapping & bvm) static
DimOp tensor operand is modified inplace.
This allows leaving dead tensors behind that will get DCE'd.
Definition at line 504 of file ComprehensiveBufferize.cpp.
References mlir::failure(), lookup(), and mlir::success().
bufferize() [3/7]
static LogicalResult bufferize (OpBuilder & b, FuncOp funcOp, BlockAndValueMapping & bvm) static
FuncOp always creates TensorToMemRef ops.
Definition at line 516 of file ComprehensiveBufferize.cpp.
References mlir::OpBuilder::create(), mlir::Type::dyn_cast(), getContiguousOrUnrankedMemRefType(), getDynamicMemRefType(), map(), mlir::OpBuilder::setInsertionPointToStart(), and mlir::success().
bufferize() [4/7]
static LogicalResult bufferize (OpBuilder & b, ReturnOp returnOp, BlockAndValueMapping & bvm) static
ReturnOp always creates memref::TensorLoadOp.
Definition at line 539 of file ComprehensiveBufferize.cpp.
References mlir::OpBuilder::create(), mlir::failure(), lookup(), mlir::OpBuilder::setInsertionPoint(), and mlir::success().
bufferize() [5/7]
static LogicalResult bufferize (OpBuilder & b, SubTensorOp subTensorOp, BlockAndValueMapping & bvm) static
Bufferize SubTensorOp to subview with optional alloc + copy depending on whether or not it is marked inplaceable.
Note that getMatchingOpResult on a SubTensorOp always returns null. As consequence a SubTensorOp always alloc + copy when taken in isolation.
If not inplaceable, copy.
Definition at line 563 of file ComprehensiveBufferize.cpp.
References mlir::Type::cast(), mlir::OpBuilder::create(), createNewAllocDeallocPairForShapedValue(), DBGS, mlir::failure(), getInPlace(), mlir::Value::getType(), lookup(), map(), mlir::OpBuilder::setInsertionPoint(), mlir::OpBuilder::setInsertionPointAfter(), mlir::success(), and True.
bufferize() [6/7]
static LogicalResult bufferize (OpBuilder & b, SubTensorInsertOp subTensorInsertOp, BlockAndValueMapping & bvm) static
Definition at line 608 of file ComprehensiveBufferize.cpp.
References mlir::Type::cast(), mlir::Value::cast(), mlir::OpBuilder::create(), createNewAllocDeallocPairForShapedValue(), DBGS, mlir::Value::dyn_cast(), mlir::failure(), mlir::Value::getDefiningOp(), getInPlace(), mlir::Value::getType(), lookup(), map(), None, mlir::OpBuilder::setInsertionPoint(), mlir::OpBuilder::setInsertionPointAfter(), mlir::success(), and True.
bufferize() [7/7]
static LogicalResult bufferize (OpBuilder & b, VectorTransferOpInterface op, BlockAndValueMapping & bvm) static
transfer_read from buffer always reads from the bufferized op.source().
Definition at line 673 of file ComprehensiveBufferize.cpp.
References mlir::OpBuilder::create(), createNewAllocDeallocPairForShapedValue(), DBGS, mlir::failure(), getInPlace(), lookup(), map(), mlir::OpBuilder::setInsertionPoint(), mlir::OpBuilder::setInsertionPointAfter(), mlir::success(), and True.
bufferizeFuncOpInternals()
static LogicalResult bufferizeFuncOpInternals (FuncOp funcOp, BlockAndValueMapping & bvm, const DenseMap< FuncOp, SmallVector< int64_t >> & tiedResultsMap) static
Start by bufferizing funcOp arguments.
Definition at line 886 of file ComprehensiveBufferize.cpp.
References mlir::WalkResult::advance(), bufferize(), DBGS, mlir::Operation::emitError(), mlir::failed(), mlir::failure(), mlir::Operation::getOperandTypes(), mlir::Operation::getResultTypes(), inPlaceAnalysisFuncOpInternals(), mlir::DialectRegistry::insert(), mlir::WalkResult::interrupt(), kInPlaceResultsAttrName, mlir::PostOrder, mlir::Operation::removeAttr(), mlir::success(), and mlir::WalkResult::wasInterrupted().
bufferizeToReadOnly()
static bool bufferizeToReadOnly (OpOperand & operand) static
Return true if operand bufferizes to a buffer that is known to never be written.
Definition at line 807 of file ComprehensiveBufferize.cpp.
References mlir::detail::IROperandBase::getOwner().
Referenced by subTensorUseBufferizesToReadOnly().
bufferizeToWriteable()
static bool bufferizeToWriteable (OpOperand & opOperand) static
Return false if either:
opOperand is produced by a constant op. For now this is assumed to be bufferized to a GlobalMemrefOp that cannot be written. Generalize in the future. 2.opOperand is a BlockArgument of a FuncOp that is not known to be bufferizable inplace. Return true otherwise.
Definition at line 767 of file ComprehensiveBufferize.cpp.
References mlir::Value::dyn_cast(), mlir::IROperand< DerivedT, IRValueT >::get(), mlir::Value::getDefiningOp(), getInPlace(), and True.
Referenced by isBufferizableInPlace().
createNewAllocDeallocPairForShapedValue()
static Value createNewAllocDeallocPairForShapedValue (OpBuilder & b, Location loc, Value shapedValue, SmallVector< Value, 4 > dynOperands = {}) static
Create an Allocop/DeAllocOp pair, where the AllocOp is after shapedValue.getDefiningOp (or at the top of the block in case of a bbArg) and the DeallocOp is at the end of the block.
Definition at line 352 of file ComprehensiveBufferize.cpp.
References mlir::Type::cast(), mlir::OpBuilder::create(), mlir::Type::dyn_cast(), mlir::Value::dyn_cast(), mlir::detail::enumerate(), getContiguousMemRefType(), mlir::Value::getDefiningOp(), mlir::Operation::getLoc(), mlir::Value::getParentBlock(), mlir::Block::getTerminator(), mlir::Value::getType(), mlir::Type::isa(), mlir::ShapedType::kDynamicSize, mlir::OpBuilder::setInsertionPoint(), mlir::OpBuilder::setInsertionPointAfter(), and mlir::OpBuilder::setInsertionPointToStart().
Referenced by allocateBuffersForResults(), and bufferize().
dominatesAllOtherUses()
static bool dominatesAllOtherUses (OpOperand & dominator, const DominanceInfo & domInfo) static
Return true if dominator.getOwner() dominates all other uses of dominator.get().
Definition at line 833 of file ComprehensiveBufferize.cpp.
References mlir::IROperand< DerivedT, IRValueT >::get(), mlir::OpOperand::getOperandNumber(), mlir::detail::IROperandBase::getOwner(), mlir::Value::getUses(), and mlir::DominanceInfo::properlyDominates().
Referenced by analyzeInPlaceSubTensor().
finalizeBufferAllocation()
static void finalizeBufferAllocation (OpBuilder & b, LinalgOp op, ValueRange inputs, ValueRange outputs, BlockAndValueMapping & bvm) static
Definition at line 456 of file ComprehensiveBufferize.cpp.
References map().
Referenced by bufferize().
getContiguousMemRefType()
static MemRefType getContiguousMemRefType (ShapedType shapedType, ArrayRef< AffineMap > layout = {}, unsigned addressSpace = 0) static
Return a contiguous MemRefType (i.e.
with canonical/empty layout map) with the same shape as shapedType and specified layout and addressSpace.
Definition at line 306 of file ComprehensiveBufferize.cpp.
References mlir::Type::cast(), and mlir::Type::dyn_cast().
Referenced by createNewAllocDeallocPairForShapedValue(), and getContiguousOrUnrankedMemRefType().
getContiguousOrUnrankedMemRefType()
static Type getContiguousOrUnrankedMemRefType (Type type, ArrayRef< AffineMap > layout = {}, unsigned addressSpace = 0) static
Return a contiguous MemRefType (i.e.
with canonical/empty layout map) with the same shape as shapedType and specified layout and addressSpace or an UnrankedMemRefType otherwise.
Definition at line 320 of file ComprehensiveBufferize.cpp.
References mlir::Type::cast(), getContiguousMemRefType(), mlir::getElementTypeOrSelf(), and mlir::Type::isa().
Referenced by bufferize().
getDynamicMemRefType()
static MemRefType getDynamicMemRefType (RankedTensorType tensorType, unsigned addressSpace = 0) static
Return a MemRefType to which the tensorType can be bufferized in a composable fashion.
The layout must be the most dynamic possible and canonicalize away once bufferization is finished.
Definition at line 333 of file ComprehensiveBufferize.cpp.
References mlir::ShapedType::kDynamicStrideOrOffset, and mlir::makeStridedLinearLayoutMap().
Referenced by bufferize().
getInPlace() [1/2]
static InPlaceSpec getInPlace (OpResult opResult) static
Get the InPlaceSpec attribute entry kInPlaceResultsAttrName for opResult.
If the result is InPlaceSpec::True, the use-def chain analysis has guaranteed that no subsequent read of the tensor value occurs and the result can be buferized inPlace. If no InPlaceSpec attribute has been set for opResult, return InPlaceSpec::None.
Definition at line 234 of file ComprehensiveBufferize.cpp.
References mlir::Attribute::dyn_cast_or_null(), mlir::Operation::getAttr(), mlir::OpResult::getOwner(), mlir::OpResult::getResultNumber(), kInPlaceResultsAttrName, None, and symbolize().
Referenced by allocateBuffersForResults(), bufferize(), bufferizeToWriteable(), and subTensorUseBufferizesToReadOnly().
getInPlace() [2/2]
static InPlaceSpec getInPlace (BlockArgument bbArg) static
Get inPlace information for bbArg.
If it does not come from a function, return InPlaceSpec::False.
Definition at line 251 of file ComprehensiveBufferize.cpp.
References False, mlir::BlockArgument::getArgNumber(), mlir::BlockArgument::getOwner(), mlir::Block::getParentOp(), None, and True.
getMatchingOpResult() [1/4]
OpResult getMatchingOpResult (LinalgOp linalgOp, OpOperand & opOperand)
Return the OpResult that matches an operand.
Return null if no such result exists.
Definition at line 108 of file ComprehensiveBufferize.cpp.
References mlir::IROperand< DerivedT, IRValueT >::get(), mlir::OpOperand::getOperandNumber(), mlir::Value::getType(), and mlir::Type::isa().
Referenced by allocateBuffersForResults(), getMatchingOpResult(), and inPlaceAnalysisFuncOpInternals().
getMatchingOpResult() [2/4]
OpResult getMatchingOpResult (VectorTransferOpInterface op, OpOperand & opOperand)
Return the OpResult that matches an operand.
Return null if no such result exists.
Definition at line 134 of file ComprehensiveBufferize.cpp.
References mlir::IROperand< DerivedT, IRValueT >::get(), mlir::Value::getType(), and mlir::Type::isa().
getMatchingOpResult() [3/4]
OpResult getMatchingOpResult (SubTensorInsertOp op, OpOperand & opOperand)
Return the OpResult that matches an operand.
Return null if no such result exists.
Definition at line 144 of file ComprehensiveBufferize.cpp.
References mlir::IROperand< DerivedT, IRValueT >::get().
getMatchingOpResult() [4/4]
OpResult getMatchingOpResult (OpOperand & opOperand)
Determine which results may be reused inplace by the bufferization patterns of bufferizeFuncOpInternals.
The inplace analysis uses this information along with interfering read analysis to determine which op results reuse the same buffer as some operand.
Definition at line 155 of file ComprehensiveBufferize.cpp.
References getMatchingOpResult(), and mlir::detail::IROperandBase::getOwner().
hasInterferingTensorRead()
bool hasInterferingTensorRead (OpOperand & opOperand, const DominanceInfo & domInfo)
Determine whether any subsequent read of the tensor opOperand may occur.
For now, this assumes any use is a read. If any use of the tensor does not properly dominate opOperand.getOwner(), then the tensor cannot be bufferized inPlace.
Definition at line 734 of file ComprehensiveBufferize.cpp.
References DBGS, mlir::DominanceInfo::dominates(), mlir::IROperand< DerivedT, IRValueT >::get(), mlir::OpOperand::getOperandNumber(), mlir::detail::IROperandBase::getOwner(), mlir::Value::getType(), mlir::Value::getUses(), mlir::Type::isa(), and mlir::DominanceInfo::properlyDominates().
Referenced by isBufferizableInPlace().
inPlaceAnalysisFuncOpInternals()
static void inPlaceAnalysisFuncOpInternals (FuncOp funcOp, const DominanceInfo & domInfo) static
Analyze the internals of a FuncOp to determine inplaceable ops.
Definition at line 864 of file ComprehensiveBufferize.cpp.
References analyzeInPlaceSubTensor(), DBGS, getMatchingOpResult(), mlir::Operation::getOpOperands(), isBufferizableInPlace(), and setInPlaceOpResult().
Referenced by bufferizeFuncOpInternals().
isBufferizableInPlace()
static bool isBufferizableInPlace (OpOperand & opOperand, const DominanceInfo & domInfo) static
Return false if either:
opOperand is produced by a constant op. For now this is assumed to be bufferized to a GlobalMemrefOp that cannot be written. Generalize in the future. 2.opOperand is a BlockArgument of a FuncOp that is not known to be bufferizable inplace. 3.opOperand has an interfering tensor read. Return true otherwise.
Definition at line 799 of file ComprehensiveBufferize.cpp.
References bufferizeToWriteable(), and hasInterferingTensorRead().
Referenced by inPlaceAnalysisFuncOpInternals().
lookup()
static Value lookup (BlockAndValueMapping & bvm, Value key) static
Wrapper for better debugging.
Definition at line 281 of file ComprehensiveBufferize.cpp.
References mlir::Operation::dump(), mlir::Value::dyn_cast(), mlir::Value::getDefiningOp(), mlir::Value::getParentBlock(), mlir::Operation::getParentOfType(), mlir::Block::getParentOp(), mlir::Value::getType(), mlir::Type::isa(), mlir::BlockAndValueMapping::lookup(), and mlir::BlockAndValueMapping::lookupOrNull().
Referenced by allocateBuffersForResults(), bufferize(), mlir::detail::InterfaceMap::contains(), mlir::AbstractOperation::hasTrait(), mlir::detail::InterfaceMap::InterfaceMap(), mlir::detail::InterfaceMap::lookup(), and mlir::ContractionOpLowering::matchAndRewrite().
map() [1/2]
static void map (BlockAndValueMapping & bvm, ValueRange keys, ValueRange values) static
Wrapper for better debugging.
Definition at line 267 of file ComprehensiveBufferize.cpp.
References DBGS, and mlir::BlockAndValueMapping::map().
Referenced by acceptBitWidth(), addDomainConstraints(), mlir::FlatAffineConstraints::addLowerOrUpperBound(), addNamedOpBuilders(), allocateBuffersForResults(), mlir::linalg::applyMapToValues(), bufferize(), buildVectorRead(), buildVectorWrite(), calculateImplicitMap(), canonicalizeLoopBounds(), mlir::canonicalizeMapAndOperands(), mlir::canonicalizeSetAndOperands(), computeIterationGraph(), computeLoopIndependentUpperBound(), createFoldedComposedAffineApply(), mlir::python::PyAffineExpr::createFromCapsule(), mlir::python::PyIntegerSet::createFromCapsule(), denseUnitStrides(), mlir::vector::distributPointwiseVectorOp(), finalizeBufferAllocation(), findSparseAnnotations(), fuseElementwiseOpsImpl(), fuseWithReshapeByExpansion(), genBuffers(), generateCopy(), generateTransferOpSlices(), genInvariants(), genTensorLoad(), genTensorStore(), mlir::MemRefAccess::getAccessMap(), mlir::AffineMap::getAsOpaquePointer(), getCollapsedOutputDimFromInputShape(), mlir::getConstantTripCount(), mlir::AffineMap::getContext(), mlir::MutableAffineMap::getContext(), getDimMap(), getExpandedDimToCollapsedDimMap(), mlir::AffineMap::getFromOpaquePointer(), mlir::getLargestDivisorOfTripCount(), mlir::AffineBound::getMap(), mlir::AffineMap::getNumDims(), mlir::AffineMap::getNumInputs(), mlir::AffineMap::getNumResults(), mlir::AffineMap::getNumSymbols(), mlir::AffineBound::getOperands(), mlir::gpu::getProcessor(), mlir::AffineMap::getResult(), mlir::AffineMap::getResults(), getShapeDefiningLoopRange(), mlir::AffineDmaWaitOp::getTagMapAttrName(), mlir::Builder::getType(), mlir::FlatAffineConstraints::getUniverse(), inferTransposeResultType(), initializeAliases(), inlineRegionAndEmitStore(), mlir::detail::NestedAnalysisMap::invalidate(), mlir::ConvertToLLVMPattern::isConvertibleAndHasIdentityMaps(), mlir::AffineMap::isFunctionOfSymbol(), isUnitDimExpansionOnly(), linalgOpToLoopsImpl(), linearizeCollapsedDims(), logFailure(), mlir::makeComposedAffineApply(), mlir::linalg::makeTiledShapes(), mlir::linalg::AffineMinRangeCanonicalizationPattern::matchAndRewrite(), mlir::linalg::ConvOpVectorization< ConvOp, N >::matchAndRewrite(), TransferReadExtractPattern::matchAndRewrite(), TransferWriteInsertPattern::matchAndRewrite(), TransferReadPermutationLowering::matchAndRewrite(), TransferWritePermutationLowering::matchAndRewrite(), TransferOpReduceRank::matchAndRewrite(), mlir::MutableAffineMap::MutableAffineMap(), mlir::normalizeAffineParallel(), mlir::AffineMap::operator bool(), mlir::AffineExpr::operator!(), mlir::AffineMap::operator!=(), mlir::AffineMap::operator==(), outlineKernelFuncImpl(), parseAffineApplyOp(), parseAffineMapWithMinMax(), mlir::detail::Parser::parseAttribute(), mlir::DialectAsmParser::parseAttribute(), mlir::OpAsmParser::parseAttribute(), parseBound(), mlir::detail::Parser::parseFloatFromIntegerLiteral(), mlir::detail::Parser::parseIntegerSetReference(), mlir::detail::Parser::parseMemRefType(), mlir::detail::Parser::parseOptionalAttributeWithToken(), parseTransferReadOp(), printBound(), printDenseElementsAttrImpl(), remainsLegalAfterInline(), mlir::AffineExpr::replace(), replaceUnitDims(), mlir::FlatAffineConstraints::setIdValues(), mlir::MemRefType::Builder::setMemorySpace(), mlir::sinkOperationsIntoLaunchOp(), specializeForLoopForUnrolling(), specializeParallelLoopForUnrolling(), vectorizeAsLinalgGeneric(), mlir::LLVM::detail::vectorOneToOneRewrite(), verify(), verifyDimMap(), verifyNamedStructuredOp(), verifyOutputShape(), verifyReshapeLikeShapes(), and mlir::AsmState::~AsmState().
map() [2/2]
static void map (BlockAndValueMapping & bvm, Value key, Value value) static
Wrapper for better debugging.
Definition at line 275 of file ComprehensiveBufferize.cpp.
References DBGS, and mlir::BlockAndValueMapping::map().
setInPlaceOpResult()
static void setInPlaceOpResult (OpResult opResult, InPlaceSpec inPlace = InPlaceSpec::True) static
Mark whether OpResult can actually be bufferized inplace.
If inPlace is InPlaceSpec::True, the use-def chain analysis has guaranteed that no subsequent write would occur to the bufferized tensor value (i.e. the result can be bufferized inPlace).
Definition at line 208 of file ComprehensiveBufferize.cpp.
References DBGS, mlir::Attribute::dyn_cast_or_null(), mlir::Operation::getAttr(), mlir::Operation::getNumResults(), mlir::OpResult::getOwner(), mlir::OpResult::getResultNumber(), kInPlaceResultsAttrName, None, mlir::Operation::setAttr(), and stringify().
Referenced by analyzeInPlaceSubTensor(), and inPlaceAnalysisFuncOpInternals().
stringify()
static StringRef stringify (InPlaceSpec val) static
Definition at line 184 of file ComprehensiveBufferize.cpp.
References False, None, and True.
Referenced by parseOptionalLLVMKeyword(), and setInPlaceOpResult().
subTensorUseBufferizesToReadOnly()
static bool subTensorUseBufferizesToReadOnly (OpOperand & operand) static
Assume operand is a use of a subTensorOp.
Return true if this use bufferizes to a buffer that is known to never be written. Note: This function takes into consideration uses of subTensorOp and whether the owner of those uses is inplaceable. This needs to be run in postorder to provide the most accurate analysis; otherwise it is conservative.
Definition at line 819 of file ComprehensiveBufferize.cpp.
References bufferizeToReadOnly(), mlir::IROperand< DerivedT, IRValueT >::get(), mlir::Value::getDefiningOp(), getInPlace(), mlir::OpOperand::getOperandNumber(), mlir::detail::IROperandBase::getOwner(), and True.
Referenced by analyzeInPlaceSubTensor().
symbolize()
static Optional<InPlaceSpec> symbolize (StringRef str) static
Definition at line 196 of file ComprehensiveBufferize.cpp.
References False, None, and True.
Referenced by getInPlace().
Variable Documentation
kInPlaceResultsAttrName
constexpr StringLiteral kInPlaceResultsAttrName = "__inplace_results_attr__"
Attribute marker to specify op results that can be bufferized inPlace.
Definition at line 175 of file ComprehensiveBufferize.cpp.
Referenced by bufferizeFuncOpInternals(), getInPlace(), and setInPlaceOpResult().