MLIR: lib/Dialect/SCF/Transforms/Utils.cpp File Reference
Utils.cpp File Reference
#include "mlir/Dialect/SCF/Utils.h"
#include "mlir/Dialect/SCF/SCF.h"
#include "mlir/Dialect/StandardOps/IR/Ops.h"
#include "mlir/IR/BlockAndValueMapping.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/Transforms/RegionUtils.h"
#include "llvm/ADT/SetVector.h"
Functions
static std::pair< AffineExpr, AffineExpr > getMinMaxLoopIndVar (Value lbVal, Value ubVal, Value stepVal, SmallVectorImpl< Value > &dims, SmallVectorImpl< Value > &symbols)
Given the lbVal, ubVal and stepVal of a loop, append lbVal and ubVal to dims and stepVal to symbols.
Function Documentation
getMinMaxLoopIndVar()
static std::pair<AffineExpr, AffineExpr> getMinMaxLoopIndVar (Value lbVal, Value ubVal, Value stepVal, SmallVectorImpl< Value > & dims, SmallVectorImpl< Value > & symbols) static
Given the lbVal, ubVal and stepVal of a loop, append lbVal and ubVal to dims and stepVal to symbols.
Create new AffineDimExpr (lb and ub) and AffineSymbolExpr (step) with positions matching the newly appended values. Then create a min expression (i.e. lb) and a max expression (i.e. lb + step * floordiv(ub -1 - lb, step).
Definition at line 156 of file Utils.cpp.
References mlir::floorDiv(), mlir::getAffineDimExpr(), mlir::getAffineSymbolExpr(), and mlir::Value::getContext().
Referenced by mlir::getSCFMinMaxExpr().