MLIR: lib/IR/FunctionSupport.cpp File Reference
FunctionSupport.cpp File Reference
#include "mlir/IR/FunctionSupport.h"
#include "mlir/Support/LLVM.h"
#include "llvm/ADT/BitVector.h"
Functions
void iterateIndicesExcept (unsigned totalIndices, ArrayRef< unsigned > indices, function_ref< void(unsigned)> callback)
Helper to call a callback once on each index in the range [0, totalIndices), except for the indices given in indices.
static bool isEmptyAttrDict (Attribute attr)
static void setAllArgResAttrDicts (Operation *op, StringRef attrName, ArrayRef< Attribute > attrs)
Set all of the argument or result attribute dictionaries for a function.
Function Documentation
isEmptyAttrDict()
static bool isEmptyAttrDict (Attribute attr) static
Definition at line 34 of file FunctionSupport.cpp.
References mlir::Attribute::cast().
Referenced by setAllArgResAttrDicts(), and mlir::function_like_impl::detail::setArgResAttrDict().
iterateIndicesExcept()
void iterateIndicesExcept (unsigned totalIndices, ArrayRef< unsigned > indices, function_ref< void(unsigned)> callback) inline
Helper to call a callback once on each index in the range [0, totalIndices), except for the indices given in indices.
indices is allowed to have duplicates and can be in any order.
Definition at line 18 of file FunctionSupport.cpp.
Referenced by mlir::function_like_impl::eraseFunctionArguments(), and mlir::function_like_impl::eraseFunctionResults().
setAllArgResAttrDicts()
static void setAllArgResAttrDicts (Operation * op, StringRef attrName, ArrayRef< Attribute > attrs) static
Set all of the argument or result attribute dictionaries for a function.
Definition at line 90 of file FunctionSupport.cpp.
References mlir::Operation::getContext(), isEmptyAttrDict(), mlir::Operation::removeAttr(), and mlir::Operation::setAttr().
Referenced by mlir::function_like_impl::setAllArgAttrDicts(), and mlir::function_like_impl::setAllResultAttrDicts().