MLIR: lib/IR/FunctionImplementation.cpp File Reference
FunctionImplementation.cpp File Reference
#include "mlir/IR/FunctionImplementation.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/FunctionSupport.h"
#include "mlir/IR/SymbolTable.h"
Functions
static ParseResult parseFunctionResultList (OpAsmParser &parser, SmallVectorImpl< Type > &resultTypes, SmallVectorImpl< NamedAttrList > &resultAttrs)
Parse a function result list.
template<typename AttrListT , typename AttrArrayBuildFnT >
static void addArgAndResultAttrsImpl (Builder &builder, OperationState &result, ArrayRef< AttrListT > argAttrs, ArrayRef< AttrListT > resultAttrs, AttrArrayBuildFnT &&buildAttrArrayFn)
Implementation of addArgAndResultAttrs that is attribute list type agnostic.
static void printFunctionResultList (OpAsmPrinter &p, ArrayRef< Type > types, ArrayAttr attrs)
Print a function result list.
Function Documentation
addArgAndResultAttrsImpl()
template<typename AttrListT , typename AttrArrayBuildFnT > static void addArgAndResultAttrsImpl (Builder & builder, OperationState & result, ArrayRef< AttrListT > argAttrs, ArrayRef< AttrListT > resultAttrs, AttrArrayBuildFnT && buildAttrArrayFn) static
Implementation of addArgAndResultAttrs that is attribute list type agnostic.
Definition at line 153 of file FunctionImplementation.cpp.
References mlir::OperationState::addAttribute(), mlir::function_like_impl::getArgDictAttrName(), mlir::Builder::getArrayAttr(), and mlir::function_like_impl::getResultDictAttrName().
Referenced by mlir::function_like_impl::addArgAndResultAttrs().
parseFunctionResultList()
static ParseResult parseFunctionResultList (OpAsmParser & parser, SmallVectorImpl< Type > & resultTypes, SmallVectorImpl< NamedAttrList > & resultAttrs) static
Parse a function result list.
function-result-list ::= function-result-list-parens | non-function-type function-result-list-parens ::= () | (function-result-list-no-parens) function-result-list-no-parens ::= function-result (, function-result)* function-result ::= type attribute-dict?
Definition at line 102 of file FunctionImplementation.cpp.
References mlir::failed(), mlir::failure(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::parseOptionalComma(), mlir::OpAsmParser::parseOptionalLParen(), mlir::OpAsmParser::parseOptionalRParen(), mlir::OpAsmParser::parseRParen(), mlir::OpAsmParser::parseType(), mlir::succeeded(), and mlir::success().
Referenced by mlir::function_like_impl::parseFunctionSignature().
printFunctionResultList()
static void printFunctionResultList (OpAsmPrinter & p, ArrayRef< Type > types, ArrayAttr attrs) static
Print a function result list.
The provided attrs must either be null, or contain a set of DictionaryAttrs of the same arity as types.
Definition at line 273 of file FunctionImplementation.cpp.
References mlir::OpAsmPrinter::getStream(), mlir::OpAsmPrinter::printOptionalAttrDict(), and mlir::OpAsmPrinter::printType().
Referenced by mlir::function_like_impl::printFunctionSignature().