MLIR: lib/Conversion/LinalgToLLVM/LinalgToLLVM.cpp File Reference
LinalgToLLVM.cpp File Reference
#include "mlir/Conversion/LinalgToLLVM/LinalgToLLVM.h"
#include "../PassDetail.h"
#include "mlir/Conversion/AffineToStandard/AffineToStandard.h"
#include "mlir/Conversion/SCFToStandard/SCFToStandard.h"
#include "mlir/Conversion/StandardToLLVM/ConvertStandardToLLVM.h"
#include "mlir/Conversion/StandardToLLVM/ConvertStandardToLLVMPass.h"
#include "mlir/Conversion/VectorToLLVM/ConvertVectorToLLVM.h"
#include "mlir/Conversion/VectorToSCF/VectorToSCF.h"
#include "mlir/Dialect/LLVMIR/LLVMDialect.h"
#include "mlir/Dialect/Linalg/IR/LinalgOps.h"
#include "mlir/Dialect/Linalg/IR/LinalgTypes.h"
#include "mlir/Dialect/Linalg/Passes.h"
#include "mlir/Dialect/SCF/SCF.h"
#include "mlir/IR/AffineExpr.h"
#include "mlir/IR/AffineMap.h"
#include "mlir/IR/Attributes.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/MLIRContext.h"
#include "mlir/IR/Operation.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/IR/Types.h"
#include "mlir/Support/LogicalResult.h"
#include "mlir/Transforms/DialectConversion.h"
#include "mlir/Transforms/Passes.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/Type.h"
#include "llvm/Support/Allocator.h"
#include "llvm/Support/ErrorHandling.h"
Functions
template<typename T >
static Type getPtrToElementType (T containerType, LLVMTypeConverter &lowering)
static Type convertRangeType (RangeType t, LLVMTypeConverter &converter)
Convert the given range descriptor type to the LLVMIR dialect.
Function Documentation
convertRangeType()
static Type convertRangeType (RangeType t, LLVMTypeConverter & converter) static
Convert the given range descriptor type to the LLVMIR dialect.
Range descriptor contains the range bounds and the step as 64-bit integers.
struct { int64_t min; int64_t max; int64_t step; };
Definition at line 61 of file LinalgToLLVM.cpp.
References mlir::TypeConverter::convertType(), mlir::detail::enumerate(), mlir::failed(), mlir::failure(), mlir::Builder::getI64ArrayAttr(), mlir::LLVM::LLVMStructType::getLiteral(), mlir::getStridesAndOffset(), mlir::ShapedType::isDynamicStrideOrOffset(), mlir::ConversionPatternRewriter::replaceOp(), mlir::RewriterBase::replaceOpWithNewOp(), mlir::MemRefDescriptor::setAllocatedPtr(), mlir::success(), and mlir::MemRefDescriptor::undef().
Referenced by mlir::populateLinalgToLLVMConversionPatterns().
getPtrToElementType()
template<typename T > static Type getPtrToElementType (T containerType, LLVMTypeConverter & lowering) static
Definition at line 48 of file LinalgToLLVM.cpp.
References mlir::TypeConverter::convertType(), and mlir::LLVM::LLVMPointerType::get().