MLIR: lib/Transforms/MemRefDataFlowOpt.cpp File Reference
MemRefDataFlowOpt.cpp File Reference
#include "PassDetail.h"
#include "mlir/Analysis/AffineAnalysis.h"
#include "mlir/Analysis/Utils.h"
#include "mlir/Dialect/Affine/IR/AffineOps.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/Dialect/StandardOps/IR/Ops.h"
#include "mlir/IR/Dominance.h"
#include "mlir/Support/LogicalResult.h"
#include "mlir/Transforms/Passes.h"
#include "llvm/ADT/SmallPtrSet.h"
#include <algorithm>
Macros
#define DEBUG_TYPE "memref-dataflow-opt"
Functions
static bool storeMayReachLoad (Operation *storeOp, Operation *loadOp, unsigned minSurroundingLoops)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "memref-dataflow-opt"
Definition at line 29 of file MemRefDataFlowOpt.cpp.
Function Documentation
storeMayReachLoad()
static bool storeMayReachLoad (Operation * storeOp, Operation * loadOp, unsigned minSurroundingLoops) static
Definition at line 94 of file MemRefDataFlowOpt.cpp.
References mlir::checkMemrefAccessDependence(), mlir::Operation::erase(), mlir::OpState::erase(), mlir::failed(), mlir::failure(), mlir::AffineReadOpInterface::getMemRef(), mlir::getNestingDepth(), mlir::getNumCommonSurroundingLoops(), mlir::Value::getType(), mlir::Value::getUsers(), mlir::AffineReadOpInterface::getValue(), mlir::hasDependence(), min(), mlir::Value::replaceAllUsesWith(), and mlir::success().