MLIR: mlir::sparse_tensor Namespace Reference
mlir::sparse_tensor Namespace Reference
Functions
SparseTensorEncodingAttr getSparseTensorEncoding (Type type)
Convenience method to get a sparse encoding attribute from a type.
Function Documentation
getSparseTensorEncoding()
SparseTensorEncodingAttr mlir::sparse_tensor::getSparseTensorEncoding (Type type)
Convenience method to get a sparse encoding attribute from a type.
Returns null-attribute for any type without an encoding.
Definition at line 182 of file SparseTensorDialect.cpp.
References mlir::Type::dyn_cast().
Referenced by computeIterationGraph(), denseUnitStrides(), findSparseAnnotations(), genBuffers(), genInvariants(), genTensorLoad(), genTensorStore(), and verify().