MLIR: mlir::LLVM::detail Namespace Reference
mlir::LLVM::detail Namespace Reference
Classes
class DebugTranslation
struct LLVMFunctionTypeStorage
Type storage for LLVM dialect function types.
struct LLVMPointerTypeStorage
Storage type for LLVM dialect pointer types.
struct LLVMStructTypeStorage
Type storage for LLVM structure types.
struct LLVMTypeAndSizeStorage
Common storage used for LLVM dialect types that need an element type and a number: arrays, fixed and scalable vectors.
class TypeFromLLVMIRTranslatorImpl
Support for translating LLVM IR types to MLIR LLVM dialect types.
class TypeToLLVMIRTranslatorImpl
Support for translating MLIR LLVM dialect types to LLVM IR.
Functions
LogicalResult oneToOneRewrite (Operation *op, StringRef targetOp, ValueRange operands, LLVMTypeConverter &typeConverter, ConversionPatternRewriter &rewriter)
Replaces the given operation "op" with a new operation of type "targetOp" and given operands.
LogicalResult vectorOneToOneRewrite (Operation *op, StringRef targetOp, ValueRange operands, LLVMTypeConverter &typeConverter, ConversionPatternRewriter &rewriter)
Type parseType (DialectAsmParser &parser)
Parses an LLVM dialect type.
void printType (Type type, DialectAsmPrinter &printer)
Prints an LLVM Dialect type.
void connectPHINodes (Region &region, const ModuleTranslation &state)
For all blocks in the region that were converted to LLVM IR using the given ModuleTranslation, connect the PHI nodes of the corresponding LLVM IR blocks to the results of preceding blocks.
SetVector< Block * > getTopologicallySortedBlocks (Region &region)
Get a topologically sorted list of blocks of the given region.
llvm::Constant * getLLVMConstant (llvm::Type *llvmType, Attribute attr, Location loc, const ModuleTranslation &moduleTranslation, bool isTopLevel=true)
Create an LLVM IR constant of llvmType from the MLIR attribute attr.
llvm::Value * createIntrinsicCall (llvm::IRBuilderBase &builder, llvm::Intrinsic::ID intrinsic, ArrayRef< llvm::Value *> args={}, ArrayRef< llvm::Type *> tys={})
Creates a call to an LLVM IR intrinsic function with the given arguments.
llvm::Value * createNvvmIntrinsicCall (llvm::IRBuilderBase &builder, llvm::Intrinsic::ID intrinsic, ArrayRef< llvm::Value *> args={})
Creates a call to an LLVM IR intrinsic function with the given arguments for NVVM WMMA ops.
Function Documentation
connectPHINodes()
void mlir::LLVM::detail::connectPHINodes (Region & region, const ModuleTranslation & state)
For all blocks in the region that were converted to LLVM IR using the given ModuleTranslation, connect the PHI nodes of the corresponding LLVM IR blocks to the results of preceding blocks.
Connect the PHI nodes to the results of preceding blocks.
Definition at line 268 of file ModuleTranslation.cpp.
References mlir::Region::begin(), mlir::Region::end(), mlir::detail::enumerate(), mlir::Block::getNumArguments(), getPHISourceValue(), mlir::Block::getPredecessors(), mlir::LLVM::ModuleTranslation::lookupBlock(), mlir::LLVM::ModuleTranslation::lookupBranch(), and mlir::LLVM::ModuleTranslation::lookupValue().
Referenced by convertOmpOpRegions(), forwardPassthroughAttributes(), and mlir::LLVM::ModuleTranslation::SaveStack< T >::~SaveStack().
createIntrinsicCall()
llvm::Value * mlir::LLVM::detail::createIntrinsicCall (llvm::IRBuilderBase & builder, llvm::Intrinsic::ID intrinsic, ArrayRef< llvm::Value *> args = {}, ArrayRef< llvm::Type *> tys = {})
Creates a call to an LLVM IR intrinsic function with the given arguments.
Definition at line 317 of file ModuleTranslation.cpp.
Referenced by mlir::LLVM::ModuleTranslation::SaveStack< T >::~SaveStack().
createNvvmIntrinsicCall()
llvm::Value * mlir::LLVM::detail::createNvvmIntrinsicCall (llvm::IRBuilderBase & builder, llvm::Intrinsic::ID intrinsic, ArrayRef< llvm::Value *> args = {})
Creates a call to an LLVM IR intrinsic function with the given arguments for NVVM WMMA ops.
Handles cases where the intrinsic name is overloaded using the types of arguments supplied. Selects the correct intrinsic by inspecting the argument types.
Definition at line 326 of file ModuleTranslation.cpp.
References mlir::LLVMTranslationDialectInterface::convertOperation(), mlir::Operation::emitError(), mlir::failed(), and mlir::Operation::getName().
Referenced by mlir::LLVM::ModuleTranslation::SaveStack< T >::~SaveStack().
getLLVMConstant()
llvm::Constant * mlir::LLVM::detail::getLLVMConstant (llvm::Type * llvmType, Attribute attr, Location loc, const ModuleTranslation & moduleTranslation, bool isTopLevel = true)
Create an LLVM IR constant of llvmType from the MLIR attribute attr.
This currently supports integer, floating point, splat and dense element attributes and combinations thereof. Also, an array attribute with two elements is supported to represent a complex constant. In case of error, report it to loc and return nullptr.
Definition at line 109 of file ModuleTranslation.cpp.
References buildSequentialConstant(), mlir::Attribute::cast(), mlir::Constant, mlir::Attribute::dyn_cast(), elementType(), mlir::emitError(), mlir::Operation::getContext(), getInnermostElementType(), mlir::LLVM::ModuleTranslation::getLLVMContext(), mlir::LLVM::ModuleTranslation::lookupFunction(), and mlir::LLVM::satisfiesLLVMModule().
Referenced by forwardPassthroughAttributes(), shouldDropGlobalInitializer(), and mlir::LLVM::ModuleTranslation::SaveStack< T >::~SaveStack().
getTopologicallySortedBlocks()
SetVector< Block * > mlir::LLVM::detail::getTopologicallySortedBlocks (Region & region)
Get a topologically sorted list of blocks of the given region.
Sort function blocks topologically.
Definition at line 301 of file ModuleTranslation.cpp.
Referenced by convertOmpOpRegions(), forwardPassthroughAttributes(), and mlir::LLVM::ModuleTranslation::SaveStack< T >::~SaveStack().
oneToOneRewrite()
LogicalResult mlir::LLVM::detail::oneToOneRewrite (Operation * op, StringRef targetOp, ValueRange operands, LLVMTypeConverter & typeConverter, ConversionPatternRewriter & rewriter)
Replaces the given operation "op" with a new operation of type "targetOp" and given operands.
Definition at line 1630 of file StandardToLLVM.cpp.
References mlir::OperationState::addTypes(), mlir::TypeConverter::convertType(), mlir::OpBuilder::create(), mlir::OpBuilder::createOperation(), mlir::ConversionPatternRewriter::eraseOp(), mlir::failure(), mlir::Operation::getAttrs(), mlir::Builder::getI64ArrayAttr(), mlir::Operation::getLoc(), mlir::Operation::getNumResults(), mlir::Operation::getResult(), mlir::Operation::getResultTypes(), mlir::Value::getType(), mlir::LLVMTypeConverter::packFunctionResults(), mlir::ConversionPatternRewriter::replaceOp(), and mlir::success().
Referenced by getSrcVectorElementType(), mlir::OneToOneConvertToLLVMPattern< SourceOp, TargetOp >::matchAndRewrite(), and vectorOneToOneRewrite().
parseType()
Type mlir::LLVM::detail::parseType (DialectAsmParser & parser)
Parses an LLVM dialect type.
Parses one of the LLVM dialect types.
Definition at line 467 of file LLVMTypeSyntax.cpp.
Referenced by addNamedOpBuilders(), parseCalibratedType(), parsePDLType(), parseStructType(), and verifyShapeOrExtentTensorOp().
printType()
void mlir::LLVM::detail::printType (Type type, DialectAsmPrinter & printer)
Prints an LLVM Dialect type.
Prints the given LLVM dialect type recursively.
This leverages closedness of the LLVM dialect type system to avoid printing the dialect prefix repeatedly. For recursive structures, only prints the name of the structure when printing a self-reference. Note that this does not apply to sibling references. For example, struct<"a", (ptr<struct<"a">>)> struct<"c", (ptr<struct<"b", (ptr<struct<"c">>)>>, ptr<struct<"b", (ptr<struct<"c">>)>>)> note that "b" is printed twice.
Definition at line 136 of file LLVMTypeSyntax.cpp.
Referenced by dispatchPrint(), mlir::Block::getSublistAccess(), getTransferOpAdapter(), operator<<(), parsePDLType(), print(), printCalibratedQuantizedType(), printDenseElementsAttrImpl(), printElidedElementsAttr(), verifyShapeOrExtentTensorOp(), and mlir::AsmState::~AsmState().
vectorOneToOneRewrite()
LogicalResult mlir::LLVM::detail::vectorOneToOneRewrite (Operation * op, StringRef targetOp, ValueRange operands, LLVMTypeConverter & typeConverter, ConversionPatternRewriter & rewriter)
Definition at line 1704 of file StandardToLLVM.cpp.
References mlir::OperationState::addTypes(), mlir::MemRefDescriptor::alignedPtr(), mlir::UnrankedMemRefDescriptor::alignedPtr(), mlir::MemRefDescriptor::allocatedPtr(), mlir::UnrankedMemRefDescriptor::allocatedPtr(), mlir::Attribute::cast(), mlir::Location::cast(), mlir::Type::cast(), mlir::OpBuilder::clone(), mlir::computeRankReductionMask(), mlir::UnrankedMemRefDescriptor::computeSizes(), mlir::TypeConverter::convertType(), mlir::OpBuilder::create(), mlir::OpBuilder::createBlock(), createIndexAttrConstant(), mlir::LLVM::createLLVMCall(), mlir::OpBuilder::createOperation(), mlir::Type::dyn_cast(), elementType(), mlir::detail::enumerate(), mlir::ConversionPatternRewriter::eraseOp(), extractFromI64ArrayAttr(), extractNDVectorTypeInfo(), mlir::failed(), mlir::failure(), mlir::LLVM::LLVMArrayType::get(), mlir::LLVM::LLVMFunctionType::get(), mlir::LLVM::LLVMPointerType::get(), mlir::DenseElementsAttr::get(), mlir::LLVM::LLVMPointerType::getAddressSpace(), mlir::Operation::getAttrDictionary(), mlir::Operation::getAttrs(), mlir::Builder::getBoolAttr(), mlir::Builder::getContext(), mlir::MemRefDescriptor::getElementPtrType(), getElementPtrType(), getElementType(), mlir::getElementTypeOrSelf(), mlir::Builder::getFloatAttr(), mlir::Builder::getI32ArrayAttr(), mlir::Builder::getI32IntegerAttr(), mlir::Builder::getI32Type(), mlir::Builder::getI64ArrayAttr(), mlir::Builder::getI64IntegerAttr(), mlir::Builder::getIndexType(), mlir::LLVMTypeConverter::getIndexType(), mlir::OpBuilder::getInsertionBlock(), mlir::OpBuilder::getInsertionPoint(), mlir::Builder::getIntegerType(), mlir::Operation::getLoc(), mlir::Value::getLoc(), mlir::detail::getMemorySpaceAsInt(), getMemRefEltSizeInBytes(), mlir::Operation::getResult(), getSizeInBytes(), mlir::getStridesAndOffset(), mlir::Builder::getSymbolRefAttr(), mlir::Value::getType(), mlir::ValueRange::getType(), mlir::ValueRange::getTypes(), mlir::DataLayout::getTypeSize(), mlir::Builder::getUnknownLoc(), mlir::ElementsAttr::getValue(), mlir::LLVM::getVectorNumElements(), mlir::Builder::getZeroAttr(), handleMultidimensionalVectors(), mlir::Type::isa(), mlir::LLVM::isCompatibleType(), mlir::LLVM::isCompatibleVectorType(), mlir::ShapedType::isDynamic(), mlir::ShapedType::isDynamicStrideOrOffset(), mlir::LLVM::lookupOrCreateAlignedAllocFn(), mlir::LLVM::lookupOrCreateFreeFn(), mlir::LLVM::lookupOrCreateMallocFn(), map(), max(), mlir::UnrankedMemRefDescriptor::memRefDescPtr(), min(), nDVectorIterate(), mlir::ConversionPatternRewriter::notifyMatchFailure(), mlir::MemRefDescriptor::offset(), mlir::UnrankedMemRefDescriptor::offset(), oneToOneRewrite(), mlir::UnrankedMemRefDescriptor::rank(), mlir::ConversionPatternRewriter::replaceOp(), mlir::RewriterBase::replaceOpWithNewOp(), rewrite(), mlir::UnrankedMemRefDescriptor::setAlignedPtr(), mlir::UnrankedMemRefDescriptor::setAllocatedPtr(), mlir::OpBuilder::setInsertionPointToEnd(), mlir::OpBuilder::setInsertionPointToStart(), mlir::UnrankedMemRefDescriptor::setOffset(), mlir::UnrankedMemRefDescriptor::setSize(), mlir::UnrankedMemRefDescriptor::setStride(), mlir::MemRefDescriptor::size(), mlir::UnrankedMemRefDescriptor::size(), mlir::UnrankedMemRefDescriptor::sizeBasePtr(), mlir::ConversionPatternRewriter::splitBlock(), mlir::UnrankedMemRefDescriptor::stride(), mlir::UnrankedMemRefDescriptor::strideBasePtr(), mlir::success(), mlir::MemRefDescriptor::undef(), mlir::UnrankedMemRefDescriptor::undef(), unwrap(), and vectorType().
Referenced by mlir::VectorConvertToLLVMPattern< SourceOp, TargetOp >::matchAndRewrite().