MLIR: lib/Interfaces/ViewLikeInterface.cpp File Reference
ViewLikeInterface.cpp File Reference
#include "mlir/Interfaces/ViewLikeInterface.h"
#include "mlir/Interfaces/ViewLikeInterface.cpp.inc"
Functions
template<int64_t dynVal>
static void printOperandsOrIntegersListImpl (OpAsmPrinter &p, ValueRange values, ArrayAttr arrayAttr)
template<int64_t dynVal>
static ParseResult parseOperandsOrIntegersImpl (OpAsmParser &parser, SmallVectorImpl< OpAsmParser::OperandType > &values, ArrayAttr &integers)
Function Documentation
parseOperandsOrIntegersImpl()
template<int64_t dynVal> static ParseResult parseOperandsOrIntegersImpl (OpAsmParser & parser, SmallVectorImpl< OpAsmParser::OperandType > & values, ArrayAttr & integers) static
Definition at line 109 of file ViewLikeInterface.cpp.
References mlir::OpAsmParser::emitError(), mlir::failed(), mlir::failure(), mlir::Builder::getArrayAttr(), mlir::OpAsmParser::getBuilder(), mlir::Builder::getI64ArrayAttr(), mlir::OpAsmParser::getNameLoc(), mlir::OpAsmParser::parseAttribute(), mlir::OpAsmParser::parseLSquare(), mlir::OpAsmParser::parseOptionalComma(), mlir::OpAsmParser::parseOptionalOperand(), mlir::OpAsmParser::parseOptionalRSquare(), mlir::OpAsmParser::parseRSquare(), mlir::succeeded(), and mlir::success().
printOperandsOrIntegersListImpl()
template<int64_t dynVal> static void printOperandsOrIntegersListImpl (OpAsmPrinter & p, ValueRange values, ArrayAttr arrayAttr) static
Definition at line 74 of file ViewLikeInterface.cpp.
References mlir::Attribute::cast().